build: added flatten pom to resolve all variables, deploy snapshot to maven central for test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,7 +19,7 @@ defaults:
 jobs:
   build:
     runs-on: ubuntu-latest
-    timeout-minutes: 60
+    timeout-minutes: 20
     steps:
       - uses: actions/checkout@v4
 
@@ -28,11 +28,11 @@ jobs:
           echo "TAG_NAME=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
 
       # if no tag exists, this is expected to fail
-      - name: Switch to git tag for release
+      - name: Check if tag contains SNAPSHOT
         if: contains(env.TAG_NAME, 'SNAPSHOT') != true
         run: |
-          git fetch --all --tags -f
-          git checkout tags/${{ env.TAG_NAME }} -b ${{ env.TAG_NAME }}-tmp-branch
+          echo "Tag '$TAG_NAME' does not contain 'SNAPSHOT', failing build."
+          exit 1
 
       - name: Set up JDK 11
         uses: actions/setup-java@v4
@@ -40,9 +40,10 @@ jobs:
           distribution: 'zulu'
           java-version: 11
 
+      # push SNAPSHOT to maven central for testing
       - name: Build
         run: |
-          ./mvnw clean verify
+          ./mvnw clean deploy
 
       - name: Upload jar
         uses: actions/upload-artifact@v4
